version: '3'
services:
  geo-web:
    build: .
    ports:
      - "8098:80"  # 宿主机端口 8098 -> 容器端口 80
    restart: always
    container_name: geo-web-frontend
    # 挂载日志目录（可选）
    # volumes:
    #   - ./logs:/var/log/nginx
